<?php

return [
    // set to false and ini_set('display_errors', 0) in production
    'displayErrorDetails'               => false,
    'determineRouteBeforeAppMiddleware' => true,
    'db'                                => [
        'driver'    => 'mysql',
        'host'      => '192.168.15.3',
        'port'      => '3306',
        'database'  => 'wmpay',
        'username'  => 'ay',
        'password'  => 'Ay#@*2o17Db',
        'charset'   => 'utf8',
        'collation' => 'utf8_unicode_ci',
        // 'unix_socket' => '/tmp/mysql.sock',
        'prefix'    => '',
        'options'   => [
            \PDO::ATTR_PERSISTENT => false,
        ],
    ],
    'redis'                             => [
        [
            'host'  => '127.0.0.1',
            'port'  => '6379',
            'index' => 3,
        ],
    ],
    'key'                               => '35a7102186059dr8a1557f1e9c90ca47075d7c4e',
    'crawler'                           => [
        'host' => '47.90.98.83',
        'port' => '2345',
    ],
    'oss'                               => [
        'accessKeyId'     => 'LTAITVwqMcmO9FZn',
        'accessKeySecret' => 'xW3AjWhJxAP567FKv6rhg7axi0polo',
        'endpoint'        => 'oss-cn-hangzhou.aliyuncs.com',
        'bucket'          => 'wm2028',
    ],
    'upload'                            => __DIR__ . '/../public/uploadfiles',
    'bank'                              => [
        '工商'     => 'ICBC',
        '建设'     => 'CCB',
        '农业'     => 'ABC',
        '招商'     => 'CMB',
        '交通'     => 'BOCM',
        '中国银行'   => 'BOC',
        '光大'     => 'CEB',
        '民生'     => 'CMBC',
        '兴业'     => 'CIB',
        '中信'     => 'CITIC',
        '广发'     => 'CGB',
        '广东发展'   => 'CGB',
        '浦发'     => 'SPDB',
        '上海浦东发展' => 'SPDB',
        '平安'     => 'PAB',
        '华夏'     => 'HXBC',
        '宁波'     => 'NBCB',
        '东亚'     => 'BEA',
        '上海银行'   => 'BOS',
        '邮储'     => 'PSBC',
        '邮政'     => 'PSBC',
        '南京银行'   => 'NJCB',
        '上海农商'   => 'SRCB',
        '渤海'     => 'CBHB',
        '成都银行'   => 'BOCD',
        '北京银行'   => 'BOBJ',
        '徽商'     => 'WSB',
    ],
];
